# Generated by Django 3.0.3 on 2020-03-03 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('manufacturer', models.CharField(blank=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('body', models.TextField(blank=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(blank=True)),
                ('image', models.IntegerField(blank=True)),
            ],
        ),
    ]
