# Generated by Django 3.0.3 on 2020-03-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('garden', 'Garden goods'), ('auto', 'Auto goods'), ('build', 'Building goods')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('garden', 'Garden goods'), ('auto', 'Auto goods'), ('build', 'Building goods')], default='private', max_length=20),
        ),
    ]
