# Generated by Django 3.0.3 on 2020-03-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200307_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('garden', 'Garden goods'), ('auto', 'Auto goods'), ('build', 'Building goods'), ('unknown', 'Unknown goods')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('private', 'Draft'), ('public', 'Published')], default='private', max_length=20),
        ),
    ]
