# Generated by Django 3.0.3 on 2020-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('garden', 'Garden goods'), ('auto', 'Auto goods'), ('build', 'Building goods'), ('unknown', 'Unknown goods')], default='unknown', max_length=20),
        ),
    ]
