# Generated by Django 3.0.3 on 2020-03-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
