# Generated by Django 3.0.3 on 2020-03-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200312_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
