# Generated by Django 3.0.3 on 2020-03-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20200313_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kind',
        ),
    ]
