# Generated by Django 3.0.3 on 2020-03-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200315_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('garden', 'Garden goods'), ('auto', 'Auto goods'), ('build', 'Building goods'), ('unknown', 'Unknown goods')], default='unknown', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Subcategory'),
        ),
    ]
