# Generated by Django 3.0.3 on 2020-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200315_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slug_product',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='slug_subcategory',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
