# Generated by Django 3.0.3 on 2020-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200323_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
