# Generated by Django 3.0.3 on 2020-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200324_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
